name: Build DNG Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Force Unzip
        run: |
          7z x "dng-build.zip" -o"source" -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build dng_validate
        run: |
          $sln = (Get-ChildItem -Path "source" -Recurse -Filter "dng_validate.sln" | Select-Object -First 1).FullName
          if (-not $sln) { throw "Van ko thay file sln!" }
          
          echo "Dang build file: $sln"
          
          # Bo qua viec chi dinh Configuration/Platform de MSBuild tu lay mac dinh cua Adobe
          msbuild "$sln" /t:dng_validate

      - name: Get Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dng_validate_exe
          path: "**/dng_validate.exe"
